trigger: 
- master

pr: none

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: At Home
    steps:
    - task: nsis@1
      enabled: false
      inputs:
        scriptFile: 'pipelines\installer.nsi'

    - publish: pipelines\Top2000Installer.exe
      enabled: false
      displayName: Publishing installer
      artifact: installer
    
    - powershell: |
         Write-Host $env:SOURCEFOLDER
         $conf = Get-Content -Path 'pipelines\dosbox.conf' -Raw
         $newContent = $conf -replace "{{Source_Folder}}" , $env:SOURCEFOLDER
         New-Item "pipelines\dosbox.conf" -Value $newContent -Force
      env:
        SourceFolder: $(Build.SourcesDirectory)
        TempFolder: $(Agent.TempDirectory)

    - task: BatchScript@1
      inputs:
        filename: 'runit.bat'
        workingFolder: '$(Build.SourcesDirectory)\pipelines'