name: GitHub - $(product) site $(version) build $(counter) - 

pr: none

variables:
  major: 1
  minor: 1
  patch: 0
  version: $[format('{0}.{1}.{2}', variables['major'], variables['minor'], variables['patch'])]
  counter: $[counter(variables['version'], 0)]
  fullVersion: $[format('{0}{1}.{2}', variables['version'], variables['quality'], variables['counter'])]
  product: 'T2D'
  saName: 'chr$(product)sa$(stage)we'

trigger: 
  branches:
   include:
     - master

pool:
  name: At Home

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: At Home
    steps:
    - template: build.yml

- stage: Test
  jobs:
  - deployment: ReleaseTST
    displayName: 'Release TST'
    variables:
      stage: 'TST'
      hostName: 'dos-tst.Top2000.app'
    pool:
      name: At Home
    environment: 'TST'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: release.yml