trigger: 
- master

pr: none

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: At Home
    steps:
    - task: nsis@1
      enabled: false
      displayName: Creating Windows Installer
      inputs:
        scriptFile: 'pipelines\installer.nsi'

    - publish: pipelines\Top2000Installer.msi
      enabled: false
      displayName: Publishing installer
      artifact: installer
      
    - task: PowerShell@2
      inputs:
        filePath: 'SRC\WEB\build.ps1'
        workingDirectory: 'SRC\WEB\'
    
    - publish: SRC/WEB/BIN
      displayName: Publishing website
      artifact: web
     