trigger: 
- master

pr: none

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: At Home
    steps:
    - task: nsis@1
      enabled: false
      inputs:
        scriptFile: 'pipelines\installer.nsi'

    - publish: pipelines\Top2000Installer.exe
      enabled: false
      displayName: Publishing installer
      artifact: installer
    
    - powershell: |
         Write-Host $env:SOURCEFOLDER
         "[cpu]" | Out-File -FilePath "dosbox.conf"
         "cycles=max" | Out-File -FilePath "dosbox.conf" -Append
         "[autoexec]" | Out-File -FilePath "dosbox.conf" -Append
         "MOUNT C C:\DOS" | Out-File -FilePath "dosbox.conf" -Append
         "MOUNT S $env:SOURCEFOLDER\SRC" | Out-File -FilePath "dosbox.conf" -Append
         "S:" | Out-File -FilePath "dosbox.conf" -Append
         "cd TOOLS" | Out-File -FilePath "dosbox.conf" -Append
         "BUILD.BAT" | Out-File -FilePath "dosbox.conf" -Append
         "EXIT" | Out-File -FilePath "dosbox.conf" -Append
      env:
        SourceFolder: $(Build.SourcesDirectory)
        TempFolder: $(Agent.TempDirectory)

    - task: BatchScript@1
      inputs:
        filename: 'pipelines\runit.bat'
        workingFolder: '$(Build.SourcesDirectory)'