trigger: 
- master

pr: none

stages:
- stage: Build
  jobs:
  - job: Build
    workspace:
      clean: all
    pool:
      name: At Home
    steps:
    - task: nsis@1
      enabled: false
      inputs:
        scriptFile: 'pipelines\installer.nsi'

    - publish: pipelines\Top2000Installer.exe
      enabled: false
      displayName: Publishing installer
      artifact: installer

    - powershell: |
        Write-Host $env:SOURCEFOLDER
        $conf = Get-Content -Path 'pipelines\dosbox.conf' -Raw
        $newContent = $conf -replace "{{Source_Folder}}" , $env:SOURCEFOLDER
        New-Item "pipelines\dosbox.conf" -Value $newContent -Force
        Set-Variable SDL_VIDEODRIVER=dummy
        Start-Process -FilePath "C:\Program Files (x86)\DOSBox-0.74-3\DOSBox.exe"  -ArgumentList "-conf $env:SOURCEFOLDER\pipelines\dosbox.conf -noconsole" -PassThru -Wait
      env:
        SourceFolder: $(Build.SourcesDirectory)
        TempFolder: $(Agent.TempDirectory)
    
    - task: CmdLine@2
      enabled: false
      inputs:
        script: |
          SET SDL_VIDEODRIVER=dummy
          "C:\Program Files (x86)\DOSBox-0.74-3\DOSBox.exe" -conf C:\agent\_work\11\s\pipelines\dosbox.conf -noconsole