name: GitHub - $(product) site $(version) build $(counter) - 

pr: none

variables:
  major: 1
  minor: 0
  patch: 1
  version: $[format('{0}.{1}.{2}', variables['major'], variables['minor'], variables['patch'])]
  counter: $[counter(variables['version'], 0)]
  fullVersion: $[format('{0}{1}.{2}', variables['version'], variables['quality'], variables['counter'])]
  product: 'T2D'
  saName: 'chr$(product)sa$(stage)we'

trigger: 
  branches:
   include:
     - main

pool:
  name: At Home

stages:
- stage: Build
  jobs:
  - job: WebBuild
    displayName: 'Web build'
    pool:
      name: At Home
    steps:
    - template: web-build.yml
  - job: 
    displayName: 'VBDOS Build'
    pool:
      name: At Home
    steps:
    - template: dos-build.yml

- stage: Test
  displayName: 'Release - TST'
  jobs:
  - deployment: ReleaseTST
    displayName: 'Release TST'
    variables:
      stage: 'TST'
      hostName: 'dos-tst.Top2000.app'
    pool:
      name: At Home
    environment: 'TST'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: release.yml

- stage: Production
  displayName: 'Release - PRD'
  jobs:
  - deployment: ReleasePRD
    displayName: 'Release PRD'
    variables:
      stage: 'PRD'
      hostName: 'dos.Top2000.app'
    pool:
      name: At Home
    environment: 'PRD'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: release.yml