trigger: 
- master

pr: none

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: At Home
    steps:
    - task: nsis@1
      enabled: false
      inputs:
        scriptFile: 'pipelines\installer.nsi'

    - publish: pipelines\Top2000Installer.exe
      enabled: false
      displayName: Publishing installer
      artifact: installer
    
    - powershell: |
         Write-Host $env:SOURCEFOLDER
      env:
        SourceFolder: $(Build.SourcesDirectory)
    
    