trigger: 
- master

pr: none

pool:
  name: AtHome

steps:
- task: nsis@1
  inputs:
    scriptFile: 'pipelines\installer.nsi'

- publish: pipelines\Top2000Installer.exe
  displayName: Publishing installer
  artifact: installer