name: Build TOP2000 for MS-DOS
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        
      - name: Download TOP2000 database
        run: | 
          cd SRC\DOWNLOAD
          dotnet run .\DownloaderApp.csproj

      - name: Install dosbox
        run: choco install dosbox
          
      - name: Compile CRTINDEX.EXE
        run: |
          cd "C:\Program Files (x86)\DOSBox-0.74-3"
          $Env:SDL_VIDEODRIVER = 'dummy'
          .\DOSBox.exe -c "mount C ${{ github.workspace }}" -c "C:" -c "cd SRC\CRTINDEX" -c "build.bat" -c "EXIT" -noconsole -noautoexec | Out-Null
          type D:\a\Top2000-MSDOS\Top2000-MSDOS\SRC\CRTINDEX\OBJ\OUTPUT.TXT
          
      - name: Compile TOP2000.EXE
        run: |
          cd "C:\Program Files (x86)\DOSBox-0.74-3"
          $Env:SDL_VIDEODRIVER = 'dummy'
          .\DOSBox.exe -c "mount C D:\a\Top2000-MSDOS\Top2000-MSDOS" -c "C:" -c "cd SRC\TOP2000" -c "build.bat" -c "EXIT" -noconsole -noautoexec | Out-Null
          type D:\a\Top2000-MSDOS\Top2000-MSDOS\SRC\TOP2000\OBJ\OUTPUT.TXT
      
      - name: Create TOP2000.DAT
        run: |
          cd "C:\Program Files (x86)\DOSBox-0.74-3"
          $Env:SDL_VIDEODRIVER = 'dummy'
          .\DOSBox.exe -c "mount C D:\a\Top2000-MSDOS\Top2000-MSDOS" -c "C:" -c "cd SRC\DB" -c "build.bat" -c "EXIT" -noconsole -noautoexec | Out-Null
          type D:\a\Top2000-MSDOS\Top2000-MSDOS\SRC\DB\OUTPUT.TXT

      - name: Create TOP2000 DOS Site
        run: |
          cd "SRC\WEB"
          .\build.ps1

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TOP2000 App
          if-no-files-found: error
          path: |
            SRC\TOP2000\BIN\TOP2000.EXE
            SRC\DB\BIN\TOP2000.DAT

      - name: Archive TOP2000 DOS Site
        uses: actions/upload-artifact@v3
        with:
          name: TOP2000 Site
          path: |
            SRC\WEB\BIN
      
