name: Build TOP2000 for MS-DOS
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        
      - name: Download TOP2000 database
        run: | 
          cd D:\a\Top2000-MSDOS\Top2000-MSDOS\SRC\DownloaderApp
          dotnet run .\DownloaderApp.csproj

      - name: Install dosbox
        run: |
          choco install dosbox
          
      - name: Compile TOP2000 INDEX GEN
        run: |
          cd "C:\Program Files (x86)\DOSBox-0.74-3"
          $Env:SDL_VIDEODRIVER = 'dummy'
          .\DOSBox.exe -c "mount C D:\a\Top2000-MSDOS\Top2000-MSDOS" -c "C:" -c "cd SRC\CRTINDEX" -c "build.bat" -c "EXIT" -noconsole -noautoexec | Out-Null
          type D:\a\Top2000-MSDOS\Top2000-MSDOS\SRC\CRTINDEX\OBJ\OUTPUT.TXT
          
      - name: Compile TOP2000 MSDOS
        run: |
          cd "C:\Program Files (x86)\DOSBox-0.74-3"
          $Env:SDL_VIDEODRIVER = 'dummy'
          .\DOSBox.exe -c "mount C D:\a\Top2000-MSDOS\Top2000-MSDOS" -c "C:" -c "cd SRC\TOP2000" -c "build.bat" -c "EXIT" -noconsole -noautoexec | Out-Null
          type D:\a\Top2000-MSDOS\Top2000-MSDOS\SRC\TOP2000\OBJ\OUTPUT.TXT
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TOP2000 App
          path: |
            D:\a\Top2000-MSDOS\Top2000-MSDOS\SRC\TOP2000\BIN\TOP2000.EXE
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TOP2000 Database Gen
          path: |
            D:\a\Top2000-MSDOS\Top2000-MSDOS\SRC\CRTINDEX\BIN\CRTINDEX.EXE

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TOP2000 Databases
          path: |
            D:\a\Top2000-MSDOS\Top2000-MSDOS\SRC\DownloaderApp\editions.csv
            D:\a\Top2000-MSDOS\Top2000-MSDOS\SRC\DownloaderApp\tracks.csv
            D:\a\Top2000-MSDOS\Top2000-MSDOS\SRC\DownloaderApp\listings.csv
      
