name: Build TOP2000 for MS-DOS
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        
      - name: Download TOP2000 database
        run: | 
          cd SRC\DOWNLOAD
          dotnet run .\DownloaderApp.csproj

      - name: Install dosbox
        run: choco install dosbox
          
      - name: Compile CRTINDEX.EXE
        run: |
          cd "C:\Program Files (x86)\DOSBox-0.74-3"
          $Env:SDL_VIDEODRIVER = 'dummy'
          .\DOSBox.exe -c "mount C ${{ github.workspace }}" -c "C:" -c "cd SRC\CRTINDEX" -c "build.bat" -c "EXIT" -noconsole -noautoexec | Out-Null
          type D:\a\Top2000-MSDOS\Top2000-MSDOS\SRC\CRTINDEX\OBJ\OUTPUT.TXT
          
      - name: Compile TOP2000.EXE
        run: |
          cd "C:\Program Files (x86)\DOSBox-0.74-3"
          $Env:SDL_VIDEODRIVER = 'dummy'
          .\DOSBox.exe -c "mount C ${{ github.workspace }}" -c "C:" -c "cd SRC\TOP2000" -c "build.bat" -c "EXIT" -noconsole -noautoexec | Out-Null
          type D:\a\Top2000-MSDOS\Top2000-MSDOS\SRC\TOP2000\OBJ\OUTPUT.TXT
      
      - name: Create TOP2000.DAT
        run: |
          cd "C:\Program Files (x86)\DOSBox-0.74-3"
          $Env:SDL_VIDEODRIVER = 'dummy'
          .\DOSBox.exe -c "mount C ${{ github.workspace }}" -c "C:" -c "cd SRC\DB" -c "build.bat" -c "EXIT" -noconsole -noautoexec | Out-Null
          type D:\a\Top2000-MSDOS\Top2000-MSDOS\SRC\DB\OUTPUT.TXT

      - name: Create TOP2000 DOS Site
        run: |
          cd "SRC\WEB"
          .\build.ps1

      - name: Create App artifact
        run: |
          cd ${{ github.workspace }}\Publish\App
          copy "C:\Program Files (x86)\DOSBox-0.74-3\DOSBox.exe" DOSBox.exe
          copy "C:\Program Files (x86)\DOSBox-0.74-3\SDL_net.dll" SDL_net.dll
          copy "C:\Program Files (x86)\DOSBox-0.74-3\SDL.dll" SDL.dll
          copy ${{ github.workspace }}\SRC\TOP2000\BIN\TOP2000.EXE TOP2000.EXE
          copy ${{ github.workspace }}\SRC\DB\BIN\TOP2000.DAT TOP2000.DAT

      - name: Create 1.44mb disk artifact
        run: |
          cd "C:\Program Files (x86)\DOSBox-0.74-3"
          $Env:SDL_VIDEODRIVER = 'dummy'
          .\DOSBox.exe -c "mount C ${{ github.workspace }}" -c "C:" -c "cd SRC\TOOLS" -c "MKDISK.BAT" -c "EXIT" -noconsole -noautoexec | Out-Null

      - name: Create Raw artifact
        run: |
          cd ${{ github.workspace }}\Publish\
          mkdir RAW
          copy ${{ github.workspace }}\SRC\TOP2000\BIN\TOP2000.EXE TOP2000.EXE
          copy ${{ github.workspace }}\SRC\TOP2000\BIN\TOP2000.ICO TOP2000.ICO
          copy ${{ github.workspace }}\SRC\DB\BIN\TOP2000.DAT TOP2000.DAT

      - name: Publish App disk artifact
        uses: actions/upload-artifact@v3
        with:
          name: APP
          path: Publish\APP

      - name: Publish 1.44mb disk artifact
        uses: actions/upload-artifact@v3
        with:
          name: DISK
          path: Publish\DISK

      - name: Publish Raw disk artifact
        uses: actions/upload-artifact@v3
        with:
          name: RAW
          path: Publish\RAW

      - name: Archive TOP2000 DOS Site
        uses: actions/upload-artifact@v3
        with:
          name: Site
          path: |
            SRC\WEB\BIN
      
